### ISSUE TITLE
Reversal in line 22?

### ISSUE THREAD

**Issue by labroo2** [Lorenagb/GS_HighlyPolyploid#1]

**Comment by Lorenagb** [comment]
Hey, Marlee

It's been a mistake indeed. I somehow didn't update the files for sweetpotato (the SNP matrix has missing values and the code is indeed wrong).
The matrix have to be in a certain configuration for the operations with the allele frequency vectors to go the right way.
Please have a look at the updated version

**Comment by labroo2** [comment]
Thank you so much Lorena! I will check it out. :-) -Marlee
